### PR TITLE
Adding installation instructions

### PR DESCRIPTION
**Pull request by ghost**
Adding instructions so the user can install the plugin

### CODE REVIEW

**Review by dzmanto — APPROVED** [review]

**Comment by ghost** [comment]
@dzmanto Could you merge with the master branch?

**Comment by ghost** [comment]
I'm going to delete my repository, but I don't know if the pr code will still exist, so could you merge the code?

**Comment by dzmanto** [comment]
Hi Taconi,

How shall I merge the code?

Best regards,

Daniela

________________________________________

**Comment by ghost** [comment]
I think the [github documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request) on this topic might help.

If you want to do some research on the subject itself, the [git documentation](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) is really cool.

**Comment by dzmanto** [comment]
as discussed with Taconi in December 2023

**Review by dzmanto — APPROVED** [review]
changes are fine

**Pull request merged**
